spring.config.import=optional:secrets.properties
spring.application.name=lead-management
server.port=${PORT:8080}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Common JPA Settings
spring.jpa.open-in-view=false


# Multipart upload limits (audio recordings)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

# Prevent Jackson crash on Hibernate lazy proxies
spring.jackson.serialization.fail-on-empty-beans=false

lms.jwt.secret=${JWT_SECRET:9f7Kx2LpQ8mN4sT1zV6aBcD3eFgH7jKlP0rWxY5uIoN2qRsT8vUzC1dEfG4hJkLm}
jwt.expiration=86400000
lms.admin.email=${ADMIN_EMAIL:admin@lms.com}
lms.admin.password=${ADMIN_PASSWORD:admin123}

# lms.base-url=${LMS_BASE_URL}


# Mail Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:ourhr.futureinvosolutions@gmail.com}
spring.mail.password=${MAIL_PASSWORD:vwemieagotfvqxsj}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=${MAIL_FROM:ourhr.futureinvosolutions@gmail.com}
spring.mail.properties.mail.debug=true

# Payment Configuration
app.frontend-url=${APP_FRONTEND_URL:http://100.30.239.118}

# Cashfree Configuration
cashfree.app.id=${CASHFREE_APP_ID:YOUR_APP_ID}
cashfree.secret.key=${CASHFREE_SECRET_KEY:YOUR_SECRET_KEY}
cashfree.environment=${CASHFREE_ENV:TEST}
cashfree.webhook.url=${CASHFREE_WEBHOOK_URL:http://54.84.148.176:8080/api/payments/webhook/cashfree}